### ISSUE TITLE
Wrong album art

### ISSUE THREAD

**Issue by CartoonChess** [caarlos0/discord-applemusic-rich-presence#4]
Sorry this comes with so few details, but so far this consistently grabs the wrong album art.

Mind you, I've only tested it with a handful of albums from the same source: GameChops. Each track in the albums shows the same art, but it's always a different GameChops album. I wonder if this has anything to do with GameChops being less an artist than a label and thus creating some sort of confusion?

This is much more an FYI than a nitpick, though. Just really happy to have this working! Thanks for your hard work.

**Comment by caarlos0** [comment]
hmm, it uses the itunes api to search.. if that returns the wrong album... not much I can do unfortunately :( 

you can check with:

`https://itunes.apple.com/search?term=###TERM##&limit=1&entity=song`

Replace `###TERM###` with `artist+album+song`, replacing spaces with `+`, and see what it is returning there... (check field `ArtworkUrl100`).

**Comment by CartoonChess** [comment]
Hmm, interesting. For reference:

- Searching with artist, album, and song: [Same incorrect art as shows in Discord](https://itunes.apple.com/search?term=Tudd,+General+Offensive!+&amp;+GameChops+Smash+&amp;+Chill+7+PM+(Animal+Crossing)&limit=1&entity=song).
- Searching with artist and song: Same as above.
- Searching with album and song: [Broken image](https://itunes.apple.com/search?term=Smash+&amp;+Chill+7+PM+(Animal+Crossing)&limit=1&entity=song).
- Searching with song only: [Correct artwork](https://itunes.apple.com/search?term=7+PM+(Animal+Crossing)&limit=1&entity=song).

As you say, though, there's probably not much to be done. Thanks for taking a look though!

**Comment by caarlos0** [comment]
yeah, usually the most complete queries get the better results, but no good way to know for sure...

anyway, thank for raising the issue, will close it as discussed.

cheers!

**Comment by CartoonChess** [comment]
Just one thing to add—I found that by replacing ampersands (`&`) in the artist, album, and song with their percent-encoded equivalent (`%24`), the correct album art was returned instead. Perhaps this would improve results and avoid broken URLs? Something for reference, potentially. :)

**Comment by caarlos0** [comment]
ahhh that might be yes! wanna PR it?

you can probably use `url.QueryEscape(str)`

**Comment by caarlos0** [comment]
fixed, will release

**Comment by CartoonChess** [comment]
Great! Would've had issues fixing it myself honestly. It's working perfectly now. Thanks again!
